
name: CI

on:
 push:
    branches: [ "main" ]
  
jobs:
test:
    runs-on: ubuntu-latest
    needs: Build
    steps:

      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 17
      - uses: actions/setup-java@v2
        with:
        distribuition: 'temurin'
        java-version: '17.0.2'

      - name: Build and test with Maven
      - run: mvn clean install -Dmaven.test.skip=true
       
